# -*- coding: utf-8 -*-
"""data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Hfux079EZ4xVDLbQGuhSQkrrohP5aa_

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf
"""


import pandas as pd

df = pd.read_excel('https://github.com/kerobes97/Lets_Boot/blob/master/Web_Application/Data/2020_travel_survey.xlsx?raw=true')
df

#dashboard raw
df_10 = df.head(50)
df_10 = df_10[['S_Month', 'Days', 'T_Cost', 'SPOT', 'Accom', 'Trans', 'Partner', 'Cost_Accom', 'Cost_Food', 'Cost_Trans',
       'Cost_Shop', 'SEX', 'AGE', 'ARA']]
df_10.rename(columns = {'S_Month':'여행 월', 'Days':'여행일', 'T_Cost':'지출비용', 'SPOT':'여행 지역', 'SEX':'성별', 'AGE':'연령', 'ARA':'거주지'}, inplace=True)
df10_html = df_10.to_html()
df10_html

#busan raw
df_busan = df[df['SPOT']==21].head(15)
df_busan = df_busan[['S_Month', 'Days', 'T_Cost', 'Accom', 'Trans', 'Partner', 'Cost_Accom', 'Cost_Food', 'Cost_Trans',
       'Cost_Shop', 'SEX', 'AGE', 'ARA']]
df_busan.rename({'S_Month':'여행 월', 'Days':'여행일', 'T_Cost':'지출비용', 'SEX':'성별', 'AGE':'연령', 'ARA':'거주지'}, inplace=True)
busan_html=df_busan.to_html()
busan_html

#dashboard graph
import matplotlib.pyplot as plt
top8=df['SPOT'].value_counts().head(8)
top8=top8.rename({31:'경기도', 36:'전라남도', 38:'경상남도', 34:'충청남도', 32:'강원도', 37:'경상북도', 35:'전라북도', 21:'부산광역시'})

plt.rc('font', size=20, family='NanumBarunGothic') 
plt.rcParams["figure.figsize"] = (18,10)
top8.plot(kind='bar', alpha=0.75 ,rot=30);

ft_busan = pd.crosstab((df['SPOT']==21), df['T_Num'])

color_dict = {1: 'blue', 6: 'blue', 7:'blue', 8:'blue'}

ft_busan.iloc[0].plot(kind='bar', color=[color_dict.get(x, '#333333') for x in ft_busan.columns], alpha=1)
plt.rcParams["figure.figsize"] = (18,10)

#busan graph
m_busan = pd.crosstab((df['SPOT']==21), df['S_Month'])

color_dict = {1: 'blue', 6: 'blue', 7:'blue', 8:'blue'}

m_busan.iloc[0].plot(kind='bar', color=[color_dict.get(x, '#333333') for x in m_busan.columns], alpha=1)
plt.rcParams["figure.figsize"] = (18,10)

#seoul graph
d_seoul = df[['SPOT']==11]
m_Seoul = pd.crosstab((df['SPOT']==32), df['S_Month'])

color_dict = {1: 'blue', 6: 'blue', 7:'blue', 8:'blue'}

m_Seoul.iloc[0].plot(kind='bar', color=[color_dict.get(x, '#333333') for x in m_Seoul.columns], alpha=1)
plt.rcParams["figure.figsize"] = (18,10)